services:
  postgres:
    image: postgres:15
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  net-catalog:
    build: .
    hostname: net-catalog
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
    